<link rel="stylesheet" type="text/css" href="css/gioithieu.css" />

<div class="prd-block">
	<h2>giới thiệu về vietpro education</h2>
    <div class="about">
    	<p>Trung tâm đào tạo lập trình và đồ họa website VIETPRO được thành lập vào ngày 06/05/2009, hoạt động trong lĩnh vực đào tạo công nghệ thông tin, đặc biệt là đào tạo chuyên sâu trong lĩnh vực Lập trình, Thiết kế và đồ họa website với trụ sở chính đặt tại Hà Nội:</p>
        <p><span>Trụ sở chính</span><br />• Số 25 Ngõ 178/71 Tây Sơn, Trung Liệt, Đống Đa, Hà Nội</p>	
			<p><span>Các Cơ sở khác</span><br />• CS 1: Tầng 5 - Tòa nhà A4, Ngõ 120 Hoàng Quốc Việt, Cầu Giấy, Hà Nội<br />• CS 2: Số 23 Ngõ 178/71 Tây Sơn, Trung Liệt, Đống Đa, Hà Nội<br />Với đội ngũ giảng viên trẻ, năng động, có kiến thức chuyên môn giỏi, tận tụy và nhiệt huyết đã đưa VIETPRO nhanh chóng trở thành một trong những trung tâm uy tín hàng đầu tại Hà Nội cũng như khu vực phía bắc trong lĩnh vực đào tạo CNTT trực tuyến, một hình thức khá mới mẻ nhưng vô cùng hiệu quả và linh hoạt.</p>
        <p><span>Mục tiêu đào tạo của chúng tôi đó là</span><br />• Cung cấp những kiến thức "chuẩn", "mới nhất" đến các học viên cũng như cho cộng đồng.<br />• Đem đến cho học sinh, sinh viên cách tư duy, nghiên cứu một cách hiện đại và khoa họcĐào tạo nguồn nhân lực chất lượng cao phục vụ cho ngành CNTT nước nhà</p>
        <p><span>Môi trường đào tạo tại trung tâm</span><br />• Với cả hai hình thức đào tạo Trực tiếp & Trực tuyến, Trung Tâm VIETPRO đã mang đến cho mỗi học viên cơ hội giao lưu cùng toàn thể các bạn đam mê CNTT trên cả nước, tạo môi trường hòa đồng và thân thiện giữa các học viên của cả 3 miền bắc, trung, nam.<br />• Trung tâm luôn luôn có những giảng viên hỗ trợ Trực tiếp & Trực tuyến cho các học viên 12/24 ngoài giờ học để giải đáp những thắc mắc, vấn đề chưa hiểu trong bài học cũng như hướng dẫn các học viên cách thức để hoàn thiện đồ án cuối khóa của mình một cách tôt nhất.<br />• Ngoài ra trung tâm VIETPRO còn tổ chức nhiều hoạt động ngoại khóa bổ ích để các học viên có cơ hội giao lưu và học hỏi lẫn nhau về những vấn đề trong học tập, nghiên cứu cũng như các vấn đề xã hội lành mạnh khác</p>
        <p><span>Đội ngũ giảng viên của trung tâm chúng tôi</span><br />• Với đội ngũ giảng viên trẻ và vô cùng năng động, nhiệt huyết, tận tụy và đam mê với chuyên ngành của mình sẽ là những người thầy, người cô gần gũi với các học viên trong suốt quá trình học tập và nghiên cứu của mình.<br />• Trung tâm chúng tôi có thể tự hào về chất lượng của đội ngũ giảng viên đang công tác cho trung tâm. Họ là những người trẻ, có tài, đều là những kỹ sư, thạc sỹ năng động của thế hệ 8X từng làm việc tại nhiều vị trí như: Team Leader Outsourcing, Giảng viên của một số trường Cao đẳng & Đại học Kỹ thuật danh tiếng trên cả nước.</p>
        <p><span>Vấn đề học phí và các ưu đãi khác</span><br />• Đây chính là một trong những vấn đề mà các học viên quan tâm nhất, biết được điều đó, trung tâm đào tạo lập trình và đồ họa website VIETPRO chúng tôi đã đưa mục này vào mục chú ý thứ hai sau mục chất lượng đào tạo của mình.<br />• Ngoài việc tự hào về chất lượng đào tạo của mình, Trung Tâm VIETPRO còn tự tin khẳng định về học phí của các khóa học tại trung tâm là rất thấp so với lượng kiến thức mà chúng tôi cung cấp cho các học viên. Bởi vì chúng tôi muốn tất cả mọi người đều có thể theo học được các khóa đào tạo của trung tâm mà không phải quan tâm đến vấn đề học phí, nhất là tầng lớp Sinh viên và Học sinh.<br />• Ngoài ra, trung tâm còn có nhiều hình thức ưu đãi khác rất bổ ích khi đăng ký tham gia các khóa học như: Chế độ giảm học phí, chế độ học bổng, chế độ tặng thưởng, các Party Offline cũng như các phong trào hoạt động thể dục thể thao ngoại khóa khác…</p>
        <p id="signature"><span>vietpro education</span></p>
    </div>
</div>
